apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-testing
spec:
  selector:
    matchLabels:
      app: app-testing
  template:
    metadata:
      labels:
        app: app-testing
    spec:
      containers:
      - name: nginx
        image: nginx
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 80
